## 5.1

### a

In [1]:
a.seq <- seq(from = -4, to = 4, length.out = 20)

In [2]:
a.matrix <- matrix(data = c(F,T,T,T,F,T,T,F,F),nrow = 3, ncol = 3)

In [3]:
a.charvector <- c("don","quixote")

In [4]:
a.obs.fac <- factor(x = c("LOW","MED","HIGH"),ordered = T)
a.obs.fac

[1] LOW  MED  HIGH
Levels: HIGH < LOW < MED

In [6]:
a.obs.fac.vect <- factor(x=c("LOW","MED","LOW","MED","MED","HIGH"), levels=levels(a.obs.fac))
print(a.obs.fac.vect)

[1] LOW  MED  LOW  MED  MED  HIGH
Levels: HIGH LOW MED


In [7]:
a_list <- list(a.seq, a.matrix, a.charvector, a.obs.fac.vect)

In [8]:
#i
a_list[[2]][c(2,1),c(2,3)]

[,1]  [,2] 
[1,] FALSE FALSE
[2,]  TRUE  TRUE

In [9]:
#ii
a_list[[3]] <- sub(pattern="q",replacement = "Q",x = a_list[[3]])
a_list[[3]] <- sub(pattern="d",replacement = "D",x = a_list[[3]])
print(a_list[[3]])

[1] "Don"     "Quixote"


In [10]:
cat("\"Windmills! ATTACK!\"","\n","    -\\",a_list[[3]][1]," ", a_list[[3]][2], "/-",sep="")

"Windmills! ATTACK!"
    -\Don Quixote/-

In [11]:
#iii
a_list[[1]][a_list[[1]] > 1]

[1] 1.052632 1.473684 1.894737 2.315789 2.736842 3.157895 3.578947 4.000000

In [12]:
#iv
which(x = a_list[[4]] == "MED")

[1] 2 4 5

### b

In [13]:
b_list <- list(
    a.obs.fac.vect,
    c(3,2.1,3.3,4,1.5,4.9)
)

In [14]:
names(b_list) <- c(
    "facs",
    "nums"
)

In [15]:
b_list$oldlist <- a_list[1:3]

In [16]:
b_list

$facs
[1] LOW  MED  LOW  MED  MED  HIGH
Levels: HIGH LOW MED

$nums
[1] 3.0 2.1 3.3 4.0 1.5 4.9

$oldlist
$oldlist[[1]]
 [1] -4.0000000 -3.5789474 -3.1578947 -2.7368421 -2.3157895 -1.8947368
 [7] -1.4736842 -1.0526316 -0.6315789 -0.2105263  0.2105263  0.6315789
[13]  1.0526316  1.4736842  1.8947368  2.3157895  2.7368421  3.1578947
[19]  3.5789474  4.0000000

$oldlist[[2]]
      [,1]  [,2]  [,3]
[1,] FALSE  TRUE  TRUE
[2,]  TRUE FALSE FALSE
[3,]  TRUE  TRUE FALSE

$oldlist[[3]]
[1] "Don"     "Quixote"

In [17]:
b_list$facs[b_list$nums >= 3]

[1] LOW  LOW  MED  HIGH
Levels: HIGH LOW MED

In [18]:
#ii
b_list$flags <- rep(x=b_list$oldlist[[2]][,3], times=2)

In [19]:
b_list$flags

[1]  TRUE FALSE FALSE  TRUE FALSE FALSE

In [20]:
#iii
b_list$nums[!b_list$flags]

[1] 2.1 3.3 1.5 4.9

In [21]:
#iv
b_list$oldlist[[3]] <- "Don Quixote"

In [22]:
b_list

$facs
[1] LOW  MED  LOW  MED  MED  HIGH
Levels: HIGH LOW MED

$nums
[1] 3.0 2.1 3.3 4.0 1.5 4.9

$oldlist
$oldlist[[1]]
 [1] -4.0000000 -3.5789474 -3.1578947 -2.7368421 -2.3157895 -1.8947368
 [7] -1.4736842 -1.0526316 -0.6315789 -0.2105263  0.2105263  0.6315789
[13]  1.0526316  1.4736842  1.8947368  2.3157895  2.7368421  3.1578947
[19]  3.5789474  4.0000000

$oldlist[[2]]
      [,1]  [,2]  [,3]
[1,] FALSE  TRUE  TRUE
[2,]  TRUE FALSE FALSE
[3,]  TRUE  TRUE FALSE

$oldlist[[3]]
[1] "Don Quixote"


$flags
[1]  TRUE FALSE FALSE  TRUE FALSE FALSE

## 5.2

### a

In [23]:
person_vector <- c("Stan","Francine","Steve","Roger","Hayley","Klaus")
sex_vector <- c("M","F","M","M","F","M")
sex_vector.fac <- factor(sex_vector)

funny_vector <- c("High","Med","Low","High","Med","Med")
funny_vector.fac.levels <- factor(c("Low","Med","High"),ordered=TRUE)
funny_vector.fac <- factor(funny_vector,levels=funny_vector.fac.levels)

In [24]:
sex_vector.fac
funny_vector.fac

[1] M F M M F M
Levels: F M

[1] High Med  Low  High Med  Med 
Levels: Low Med High

In [25]:
a_df <- data.frame(person=person_vector, sex=sex_vector.fac, funny=funny_vector.fac, stringsAsFactors = FALSE)

In [26]:
a_df

person   sex funny
1 Stan     M   High 
2 Francine F   Med  
3 Steve    M   Low  
4 Roger    M   High 
5 Hayley   F   Med  
6 Klaus    M   Med

### b

In [27]:
age_vector <- c(41, 41, 15, 1600, 21, 60)

In [28]:
a_df <- cbind(a_df, age=age_vector)

In [29]:
a_df

person   sex funny age 
1 Stan     M   High    41
2 Francine F   Med     41
3 Steve    M   Low     15
4 Roger    M   High  1600
5 Hayley   F   Med     21
6 Klaus    M   Med     60

### c

In [43]:
dframe <- a_df[,c("person","age","sex","funny")]

In [44]:
dframe

person   age  sex funny
1 Stan       41 M   High 
2 Francine   41 F   Med  
3 Steve      15 M   Low  
4 Roger    1600 M   High 
5 Hayley     21 F   Med  
6 Klaus      60 M   Med

### d

In [45]:
mydata2 <- a_df

In [47]:
mydata2$age.mon <- a_df$age * 12

In [48]:
mydata2

person   age  sex funny age.mon
1 Stan       41 M   High    492  
2 Francine   41 F   Med     492  
3 Steve      15 M   Low     180  
4 Roger    1600 M   High  19200  
5 Hayley     21 F   Med     252  
6 Klaus      60 M   Med     720

In [49]:
mydata2 <- mydata2[,-5]

In [50]:
mydata2

person   age  sex funny
1 Stan       41 M   High 
2 Francine   41 F   Med  
3 Steve      15 M   Low  
4 Roger    1600 M   High 
5 Hayley     21 F   Med  
6 Klaus      60 M   Med

### e

In [51]:
mydataframe <- data.frame(cbind(mydata2, dframe))

In [56]:
mydataframe

person   age  sex funny person.1 age.1 sex.1 funny.1
1 Stan       41 M   High  Stan       41  M     High   
2 Francine   41 F   Med   Francine   41  F     Med    
3 Steve      15 M   Low   Steve      15  M     Low    
4 Roger    1600 M   High  Roger    1600  M     High   
5 Hayley     21 F   Med   Hayley     21  F     Med    
6 Klaus      60 M   Med   Klaus      60  M     Med

### f

In [57]:
mydataframe[mydataframe$sex == "F"|mydataframe$funny == "Med"|mydataframe$funny == "High",]

person   age  sex funny person.1 age.1 sex.1 funny.1
1 Stan       41 M   High  Stan       41  M     High   
2 Francine   41 F   Med   Francine   41  F     Med    
4 Roger    1600 M   High  Roger    1600  M     High   
5 Hayley     21 F   Med   Hayley     21  F     Med    
6 Klaus      60 M   Med   Klaus      60  M     Med

### g

In [63]:
mydataframe[substr(x = mydataframe$person, start=1, stop=1) == "S",]

person age sex funny person.1 age.1 sex.1 funny.1
1 Stan   41  M   High  Stan     41    M     High   
3 Steve  15  M   Low   Steve    15    M     Low