# 10.1

### a

In [1]:
vec1 <- c(2,1,1,3,2,1,0)
vec2 <- c(3,8,2,2,0,0,0)

In [2]:
#i
#Print Me
if((vec1[1]+vec2[2])==10){cat("print me")}

print me

In [3]:
#ii
#Print Me
if((vec1[1]>=2&&vec2[1]>=2)){cat("print me")}

print me

In [4]:
#iii
#no
if(all((vec2-vec1)[c(2,6)]>7)){cat("print me")}

In [5]:
#iv
#Print Me
if(!is.na(vec2[3])){cat("print me")}

print me

### b

In [6]:
ifelse(vec1+vec2>3,vec1*vec2,vec1+vec2)

[1] 6 8 3 6 2 1 0

### c

In [7]:
my_matrix <- matrix(data=c("alligator","goat","gorilla","golf"),nrow = 2, ncol= 2)
my_matrix <- matrix(as.character(1:16),4,4)
my_matrix <- matrix(c("DANDELION","Hyacinthus","Gerbera",
                     "MARIGOLD","geranium","ligularia",
                     "Pachysandra","SNAPDRAGON","GLADIOLUS"),3,3)
my_matrix <- matrix(c("GREAT","exercises","right","here"),2,2,byrow=T)

In [8]:
ifelse(any(substr(diag(my_matrix),1,1)=="g"),
       diag(my_matrix)<-"HERE",
       my_matrix<-diag(nrow = nrow(my_matrix)))

[1] 1

In [9]:
my_matrix

[,1] [,2]
[1,] 1    0   
[2,] 0    1

## 10.2

## a

In [10]:
mynum <- 0
foo <- switch(mynum,12,34,56,78,NA)
print(foo)

NULL


In [11]:
if(mynum == 1){
    foo <- 12
} else if(mynum ==2){
    foo <- 34
} else if(mynum ==3){
    foo <- 56
} else if(mynum ==4){
    foo <- 78
}else if(mynum ==5){
    foo <- NA
}

In [12]:
foo

NULL

## b

In [1]:
#i
lowdose <-12.5
meddose <- 25.3
highdose <- 58.1
doselevel <- factor(c("Low","High","High","High","Low","Med","Med"),levels=c("Low","Med","High"))


In [30]:
#ii
lowdose <-12.5
meddose <- 25.3
highdose <- 58.1
doselevel <- factor(c("Low","Low","Low","Med","Low","Med","Med"),levels=c("Low","Med","High"))

In [38]:
#iii
lowdose <- 9
meddose <- 49
highdose <- 61
doselevel <- factor(c("Low","Med","Med"),levels=c("Low","Med","High"))

In [43]:
#iv
lowdose <- 9
meddose <- 49
highdose <- 61
doselevel <- factor(c("Low","High","High","High","Low","Med","Med"),levels=c("Low","Med","High"))

In [44]:
if(any(doselevel=="High")){
    cat("First")
    
    if(lowdose >= 10){
        lowdose <- 10
    } else {
        lowdose <- lowdose / 2
    }
    
    if(meddose >= 26){
        meddose <- 26
    } 
    
    if(highdose < 60){
        highdose <- 60
    } else {
        highdose <- highdose * 1.5
    }
    
    dosage <- rep(lowdose,length = length(doselevel))
    dosage[doselevel=="Med"] <- meddose
    dosage[doselevel=="High"] <- highdose
} else {
    cat("Second")
    doselevel <- factor(x = doselevel, labels = c("Small","Large"))
    
    if(lowdose < 15 && meddose < 35){
        lowdose <- lowdose * 2
        meddose <- meddose + highdose
    }
    
    dosage <- rep(lowdose, length = length(doselevel))
    dosage[doselevel=="Large"] <- meddose
}

First

In [45]:
print(lowdose)
print(meddose)
print(highdose)
dosage

[1] 4.5
[1] 26
[1] 91.5


[1]  4.5 91.5 91.5 91.5  4.5 26.0 26.0

In [47]:
print(doselevel)

[1] Low  High High High Low  Med  Med 
Levels: Low Med High


## c

In [57]:
mynum <- 8

In [58]:
if(mynum == 0){
    output <- "zero"
} else {
    output <- switch(mynum,"one","two","three","four","five","six","seven","eight","nine")
}
cat(output)

eight

## 10.3

### a

In [73]:
loopvec1 <- 5:7
loopvec2 <- 9:6
foo <- matrix(NA,length(loopvec1), length(loopvec2))

In [74]:
loopvec2[1] * loopvec1

[1] 45 54 63

In [77]:
for(i in 1:length(loopvec2)){
    foo[,i] <- loopvec2[i] * loopvec1
}

In [78]:
foo

[,1] [,2] [,3] [,4]
[1,] 45   40   35   30  
[2,] 54   48   42   36  
[3,] 63   56   49   42

### b

In [88]:
name_vector <- c("Peter","Homer","Lois","Stewie","Maggie","Bart")
name_numbers <- rep(x = NA, length(name_vector))
name_numbers

[1] NA NA NA NA NA NA

In [89]:
for(i in 1:length(name_vector)){
    name_numbers[i] <- switch(EXPR = name_vector[i],Homer=12,Marge=34,Bart=56,Lisa=78,Maggie=90,NA)
}

In [90]:
name_numbers

[1] NA 12 NA NA 90 56

### c

In [190]:
#i - Answer: 4
mylist <- list(aa=c(3.4,1),bb=matrix(1:4,2,2),
    cc=matrix(c(T,T,F,T,F,F),3,2),dd="string here",
    ee=list(c("hello","you"),matrix(c("hello",
    "there"))),
    ff=matrix(c("red","green","blue","yellow")))

In [188]:
#ii - Answer: 0
mylist <- list("tricked you",as.vector(matrix(1:6,3,2)))

In [183]:
#iii - Answer: 2
mylist <- list(list(1,2,3),list(c(3,2),2),
    list(c(1,2),matrix(c(1,2))),
    rbind(1:10,100:91))

In [191]:
counter <- 0

for(i in 1:length(mylist)){
    member <- mylist[[i]]
    if(is.matrix(member)){
        counter = counter + 1
    } else if(is.list(member)){
        for(j in 1:length(member)){
            if(is.matrix(member[[j]])){
                counter = counter + 1
            }
        }
    }
      
}
print(counter)

[1] 4


## 10.4

### a

In [1]:
mynumbers <- c(4,5,1,2,6,2,4,6,6,2)

In [14]:
mynumbers <- c(2,2,2,2,5,2)

In [24]:
mynumbers <- 2:20

In [27]:
mynumbers <- c(10,1,10,1,2)

In [28]:
mylist <- list()
counter <- 1
mycondition <- mynumbers[counter] <= 5
while(mycondition){
    mylist[[counter]] <- diag(mynumbers[counter])
    counter <- counter + 1
    if(counter <= length(mynumbers)){
        mycondition <- mynumbers[counter] <= 5
    } else {
        myconditiona <- FALSE
    }
}

In [29]:
print(mylist)

list()


### b

In [39]:
#mynum <- 5
#mynum <- 12
mynum <- 0
RunningProduct <- 1
while(mynum >= 0){
    if(mynum == 0){
        RunningProduct <- RunningProduct
    } else{
        RunningProduct <- RunningProduct * mynum
    }
    mynum <- mynum - 1
}

In [40]:
print(RunningProduct)

[1] 1


### c

In [17]:
mystring <- "R fever"
mystring <- "beautiful"
mystring <- "ECCENTRIC"
mystring <- "ElAbOrAte"
mystring <- "eeeeek!"
index <- 1
ecount <- 0
result <- mystring
while(ecount<2 && index <= nchar(mystring)){
    CurrentChar <- substr(x = mystring, start = index, stop = index)
    
    if(tolower(CurrentChar) == "e"){
        ecount <- ecount + 1
    }
    if(tolower(CurrentChar) == "e" & ecount == 2){
        result <- substr(x = result, start = 1, stop = index - 1)
    }
    
    index <- index + 1
}
result

[1] "e"

## 10.5

### a

In [16]:
foo <- matrix(1:12,4,3)
foo

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [17]:
foo_2 <- apply(foo, MARGIN=1, sort, decreasing=TRUE)


In [18]:
apply(foo_2, 1, FUN = prod)

[1] 11880  1680    24

### b

In [25]:
matlist <- list(matrix(c(T,F,T,T),2,2),
               matrix(c("a","c","b","z","p","q"),3,2),
               matrix(1:8,2,4))
matlist

[[1]]
      [,1] [,2]
[1,]  TRUE TRUE
[2,] FALSE TRUE

[[2]]
     [,1] [,2]
[1,] "a"  "z" 
[2,] "c"  "p" 
[3,] "b"  "q" 

[[3]]
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

In [26]:
for(i in 1:length(matlist)){
    matlist[[i]] <- t(matlist[[i]])
}
matlist

[[1]]
     [,1]  [,2]
[1,] TRUE FALSE
[2,] TRUE  TRUE

[[2]]
     [,1] [,2] [,3]
[1,] "a"  "c"  "b" 
[2,] "z"  "p"  "q" 

[[3]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8

In [27]:
matlist <- list(matrix(c(T,F,T,T),2,2),
               matrix(c("a","c","b","z","p","q"),3,2),
               matrix(1:8,2,4))
matlist

[[1]]
      [,1] [,2]
[1,]  TRUE TRUE
[2,] FALSE TRUE

[[2]]
     [,1] [,2]
[1,] "a"  "z" 
[2,] "c"  "p" 
[3,] "b"  "q" 

[[3]]
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

In [28]:
lapply(matlist, FUN = t)

[[1]]
     [,1]  [,2]
[1,] TRUE FALSE
[2,] TRUE  TRUE

[[2]]
     [,1] [,2] [,3]
[1,] "a"  "c"  "b" 
[2,] "z"  "p"  "q" 

[[3]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4
[3,]    5    6
[4,]    7    8

### c

In [29]:
#i
qux <- array(96:1, dim=c(4,4,2,3))

In [48]:
apply(X = qux[,,2,],3 , FUN=diag)

[,1] [,2] [,3]
[1,] 80   48   16  
[2,] 75   43   11  
[3,] 70   38    6  
[4,] 65   33    1

In [42]:
diag(qux[,,2,1])

[1] 80 75 70 65

In [60]:
#ii


In [68]:
apply(apply(qux[,4,,],3,dim),1,sum)

[1] 12  6

## 10.6

### a

In [76]:
foo <- 5
bar <- c(2,3,1.1,4,0,4.1,3)

In [77]:
loop1.result <- rep(NA,length(bar))
loop1.result

[1] NA NA NA NA NA NA NA

In [79]:
#i
counter <- 1
while(is.finite(foo/bar[counter])){
    loop1.result[counter] <- foo/bar[counter]
    counter <- counter + 1
}

In [80]:
loop1.result

[1] 2.500000 1.666667 4.545455 1.250000       NA       NA       NA

In [81]:
#ii
loop2.result <- rep(NA, length(bar))
loop2.result

[1] NA NA NA NA NA NA NA

In [93]:
for(i in 1:length(bar)){
    if(bar[i] != 0){
        loop2.result[i] <- foo/bar[i]
    } else {
        loop2.result[i] <- NA
    }
}

In [94]:
loop2.result

[1] 2.500000 1.666667 4.545455 1.250000       NA 1.219512 1.666667

In [91]:
loop2.result <- ifelse(is.finite(foo / bar)

In [92]:
loop2.result

[1]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE

In [95]:
loop3.result <- ifelse(is.finite(foo/bar),foo/bar,NA)
loop3.result

[1] 2.500000 1.666667 4.545455 1.250000       NA 1.219512 1.666667

### b

In [141]:
mynumbers <- c(4,5,1,2,6,2,4,6,6,2)
mylist <- list()

In [142]:
#i
for(i in 1:length(mynumbers)){
    if(mynumbers[i] <= 5){
        mylist[[i]] <- diag(x=mynumbers[i])
    } else {
        break
    }
}

In [143]:
mylist

[[1]]
     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    0    1    0    0
[3,]    0    0    1    0
[4,]    0    0    0    1

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    1    0    0    0
[3,]    0    0    1    0    0
[4,]    0    0    0    1    0
[5,]    0    0    0    0    1

[[3]]
     [,1]
[1,]    1

[[4]]
     [,1] [,2]
[1,]    1    0
[2,]    0    1

In [149]:
mylist <- list()

In [150]:
i <- 1
repeat{
    
    if(mynumbers[i] <= 5){
        mylist[[i]] <- diag(x=mynumbers[i])
        i <- i +1
    } else {
        break
    }
    
    
}

In [151]:
mylist

[[1]]
     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    0    1    0    0
[3,]    0    0    1    0
[4,]    0    0    0    1

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    0    0    0    0
[2,]    0    1    0    0    0
[3,]    0    0    1    0    0
[4,]    0    0    0    1    0
[5,]    0    0    0    0    1

[[3]]
     [,1]
[1,]    1

[[4]]
     [,1] [,2]
[1,]    1    0
[2,]    0    1

### c

In [152]:
#i
matlist1 <- list(matrix(1:4,2,2),matrix(1:4),matrix(1:8,4,2))
matlist2 <- matlist1

In [181]:
#ii
matlist1 <- list(matrix(1:4,2,2),matrix(2:5,2,2),matrix(1:16,8,2))
matlist2 <- list(matrix(1:8,2,4),matrix(10:7,2,2),matrix(9:2,4,2))

In [182]:
reslist <- list()
ResListCounter <- 1
for(i in 1:length(matlist1)){
    for(j in 1:length(matlist2)){
        if(dim(matlist1[[i]])[2] == dim(matlist2[[j]])[1]){
            reslist[[ResListCounter]] <- print(matlist1[[i]] %*% matlist2[[j]])
            
        } else {
            reslist[[ResListCounter]] <- "Not Possible"
        }
        ResListCounter <- ResListCounter + 1
    }
}
reslist

     [,1] [,2] [,3] [,4]
[1,]    7   15   23   31
[2,]   10   22   34   46
     [,1] [,2]
[1,]   37   29
[2,]   56   44
     [,1] [,2] [,3] [,4]
[1,]   10   22   34   46
[2,]   13   29   45   61
     [,1] [,2]
[1,]   56   44
[2,]   75   59
     [,1] [,2] [,3] [,4]
[1,]   19   39   59   79
[2,]   22   46   70   94
[3,]   25   53   81  109
[4,]   28   60   92  124
[5,]   31   67  103  139
[6,]   34   74  114  154
[7,]   37   81  125  169
[8,]   40   88  136  184
     [,1] [,2]
[1,]   91   71
[2,]  110   86
[3,]  129  101
[4,]  148  116
[5,]  167  131
[6,]  186  146
[7,]  205  161
[8,]  224  176


[[1]]
     [,1] [,2] [,3] [,4]
[1,]    7   15   23   31
[2,]   10   22   34   46

[[2]]
     [,1] [,2]
[1,]   37   29
[2,]   56   44

[[3]]
[1] "Not Possible"

[[4]]
     [,1] [,2] [,3] [,4]
[1,]   10   22   34   46
[2,]   13   29   45   61

[[5]]
     [,1] [,2]
[1,]   56   44
[2,]   75   59

[[6]]
[1] "Not Possible"

[[7]]
     [,1] [,2] [,3] [,4]
[1,]   19   39   59   79
[2,]   22   46   70   94
[3,]   25   53   81  109
[4,]   28   60   92  124
[5,]   31   67  103  139
[6,]   34   74  114  154
[7,]   37   81  125  169
[8,]   40   88  136  184

[[8]]
     [,1] [,2]
[1,]   91   71
[2,]  110   86
[3,]  129  101
[4,]  148  116
[5,]  167  131
[6,]  186  146
[7,]  205  161
[8,]  224  176

[[9]]
[1] "Not Possible"