## 6.1

### a

In [1]:
foo <- c(13563, -14156, -14319, 16981, 12921, 11979, 9568, 8833, -12968, 8133)

In [20]:
#i
foo[is.finite(foo^75)]

[1] 4.3 2.2 2.4 3.3 3.1 3.4

In [3]:
#ii
foo[!(abs(foo^75) != (foo^75))]

[1] 13563 16981 12921 11979  9568  8833  8133

### b

In [4]:
bar <- matrix(
    c(77875.40,-35466.25,-39803.81, 27551.45, -73333.85, 55976.34, 
      23764.30, 36599.69, 76694.82, -36478.88, -70585.69, 47032.00),
    nrow = 3, 
    ncol = 4
)

In [5]:
bar

[,1]      [,2]      [,3]     [,4]     
[1,]  77875.40  27551.45 23764.30 -36478.88
[2,] -35466.25 -73333.85 36599.69 -70585.69
[3,] -39803.81  55976.34 76694.82  47032.00

In [6]:
#i
which(x=is.nan((bar^65) / Inf))

[1]  1  5  6  9 11

In [7]:
#ii
which(x=!is.nan(bar^67 + Inf))

[1]  1  2  3  4  6  7  8  9 10 12

In [8]:
which(x=bar^67!=-Inf)

[1]  1  2  3  4  6  7  8  9 10 12

In [9]:
#iii
which(x=!(bar^67==Inf))

[1]  2  3  4  5  7  8 10 11

## 6.2

### a

In [15]:
foo <- c(4.3, 2.2, NULL, 2.4, NaN, 3.3, 3.1, NULL, 3.4, NA)

In [16]:
#i
length(foo)

[1] 8

In [17]:
#ii
which(x=is.na(x=foo))

[1] 4 8

In [18]:
#iii
is.null(x=foo)

[1] FALSE

In [19]:
#iv
is.na(x=foo[8])+4/NULL

numeric(0)

### b

In [21]:
al <- c(7,7,NA,3,NA,1,1,5,NA)

In [26]:
b_list <- list(alpha=al)

In [27]:
b_list

$alpha
[1]  7  7 NA  3 NA  1  1  5 NA

In [31]:
#i
b_list$alpha

[1]  7  7 NA  3 NA  1  1  5 NA

In [32]:
#ii
b_list$beta

NULL

In [35]:
#iii
b_list$beta <- which(x=is.na(b_list$alpha))

In [36]:
b_list

$alpha
[1]  7  7 NA  3 NA  1  1  5 NA

$beta
[1] 3 5 9

## 6.3

### a

In [3]:
#i
foo <- array(data=1:36, dim=c(3,3,4))
class(foo)
attributes(foo)

[1] "array"

$dim
[1] 3 3 4

In [5]:
#ii
bar <- as.vector(foo)
class(bar)
attributes(bar)

[1] "integer"

NULL

In [9]:
#iii
baz <- as.character(bar)
class(baz)
attributes(baz)

[1] "character"

NULL

In [12]:
#iv
qux <- as.factor(baz)
class(qux)
attributes(qux)

[1] "factor"

$levels
 [1] "1"  "10" "11" "12" "13" "14" "15" "16" "17" "18" "19" "2"  "20" "21" "22"
[16] "23" "24" "25" "26" "27" "28" "29" "3"  "30" "31" "32" "33" "34" "35" "36"
[31] "4"  "5"  "6"  "7"  "8"  "9" 

$class
[1] "factor"

In [13]:
#v
quux <- bar+c(-0.1,0.1)
class(quux)
attributes(quux)

[1] "numeric"

NULL

### b

In [16]:
#i
is.numeric(foo)+is.integer(foo)

[1] 2

In [17]:
#ii
is.numeric(bar)+is.integer(bar)

[1] 2

In [18]:
#iii
is.numeric(baz)+is.integer(baz)

[1] 0

In [19]:
#iv
is.numeric(qux)+is.integer(qux)

[1] 0

In [20]:
#v
is.numeric(quux)+is.integer(quux)

[1] 1

In [21]:
b_vec <- c(
    is.numeric(foo)+is.integer(foo), 
    is.numeric(bar)+is.integer(bar),
    is.numeric(baz)+is.integer(baz), 
    is.numeric(qux)+is.integer(qux), 
    is.numeric(quux)+is.integer(quux)
)

In [22]:
b_vec.fac <- factor(b_vec, levels=c(0,1,2))

In [23]:
b_vec.fac

[1] 2 2 0 0 1
Levels: 0 1 2

In [24]:
as.numeric(b_vec.fac)

[1] 3 3 1 1 2

### c

In [31]:
c_matrix = matrix(data = c(2:13),nrow = 3, ncol=4)

In [34]:
c_matrix

[,1] [,2] [,3] [,4]
[1,] 2    5     8   11  
[2,] 3    6     9   12  
[3,] 4    7    10   13

In [36]:
as.character(as.vector(c_matrix))

[1] "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13"

### d

In [39]:
d_matrix = matrix(data = c(34,23,33,42,41,0,1,1,0,0,1,2,1,1,2),nrow=5,ncol=3)

In [40]:
print(d_matrix)

     [,1] [,2] [,3]
[1,]   34    0    1
[2,]   23    1    2
[3,]   33    1    1
[4,]   42    0    1
[5,]   41    0    2


In [44]:
#i
d_dataframe <- as.data.frame(d_matrix)

In [46]:
d_dataframe$V2 <- as.logical(d_dataframe$V2)

In [47]:
d_dataframe

V1 V2    V3
1 34 FALSE 1 
2 23  TRUE 2 
3 33  TRUE 1 
4 42 FALSE 1 
5 41 FALSE 2

In [49]:
d_dataframe$V3 <- factor(d_dataframe$V3)

In [50]:
d_dataframe

V1 V2    V3
1 34 FALSE 1 
2 23  TRUE 2 
3 33  TRUE 1 
4 42 FALSE 1 
5 41 FALSE 2