# 4.1

## a

In [1]:
avec <- c(6,9,7,3,6,7,9,6,3,6,6,7,1,9,1)
length(avec)

[1] 15

In [2]:
# i eq. 6
avec == 6
# ii
avec >= 6
# iii
avec < (6+2)
# iv
avec != 6

[1]  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE  TRUE FALSE  TRUE  TRUE FALSE
[13] FALSE FALSE FALSE

[1]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
[13] FALSE  TRUE FALSE

[1]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
[13]  TRUE FALSE  TRUE

[1] FALSE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE FALSE FALSE  TRUE
[13]  TRUE  TRUE  TRUE

### b

In [3]:
bvec <- avec[-c(1:3)]
bvec

[1] 3 6 7 9 6 3 6 6 7 1 9 1

In [4]:
barray <- array(data=bvec,dim=c(2,2,3))

In [5]:
#i
barray==((6/2)+4)
barray[barray==((6/2)+4)]
#ii
barray_2 <- barray + 2
barray_2
barray_2==((6/2)+4)
barray_2[barray_2==((6/2)+4)]

, , 1

      [,1]  [,2]
[1,] FALSE  TRUE
[2,] FALSE FALSE

, , 2

      [,1]  [,2]
[1,] FALSE FALSE
[2,] FALSE FALSE

, , 3

      [,1]  [,2]
[1,]  TRUE FALSE
[2,] FALSE FALSE

[1] 7 7

, , 1

     [,1] [,2]
[1,]    5    9
[2,]    8   11

, , 2

     [,1] [,2]
[1,]    8    8
[2,]    5    8

, , 3

     [,1] [,2]
[1,]    9   11
[2,]    3    3

, , 1

      [,1]  [,2]
[1,] FALSE FALSE
[2,] FALSE FALSE

, , 2

      [,1]  [,2]
[1,] FALSE FALSE
[2,] FALSE FALSE

, , 3

      [,1]  [,2]
[1,] FALSE FALSE
[2,] FALSE FALSE

numeric(0)

### c

In [6]:
cmatrix <- diag(x=10)
cmatrix==0

[,1]  [,2]  [,3]  [,4]  [,5]  [,6]  [,7]  [,8]  [,9]  [,10]
 [1,] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [2,]  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [3,]  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [4,]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [5,]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
 [6,]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE
 [7,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
 [8,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE
 [9,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE
[10,]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE

### d

In [7]:
any(barray==((6/2)+4))
any(barray_2==((6/2)+4))

[1] TRUE

[1] FALSE

In [8]:
all(barray==((6/2)+4))
all(barray_2==((6/2)+4))

[1] FALSE

[1] FALSE

### e

In [9]:
any(diag(cmatrix==0))

[1] FALSE

## 4.2

### a

In [10]:
foo <- c(7,1,7,10,5,9,10,3,10,8)

In [11]:
foo > 5 | foo==2

[1]  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE

In [12]:
foo[foo > 5 | foo==2]

[1]  7  7 10  9 10 10  8

### b

In [13]:
bar <- c(8,8,4,4,5,1,5,6,6,8)

In [14]:
bar <= 6 & bar != 4

[1] FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE

In [15]:
bar[bar <= 6 & bar != 4]

[1] 5 1 5 6 6

### c

In [16]:
foobar <- c(foo, bar)

In [17]:
foobar[(foobar <= 6 & foobar != 4) & (foobar > 5 | foobar==2) ]

[1] 6 6

### d

In [18]:
baz <- foo + bar
baz

[1] 15  9 11 14 10 10 15  9 16 16

In [19]:
#i
baz[baz >= 14 & baz != 15]
#ii
bazfoo <- baz / foo
bazfoo[baz / foo > 4 | baz / foo <= 2]

[1] 14 16 16

[1] 9.000000 1.571429 1.400000 2.000000 1.111111 1.500000 1.600000 2.000000

### e

In [20]:
foo[1] > 5 || foo[1] == 2

[1] TRUE

## 4.3

### a

In [21]:
foo <- c(7,5,6,1,2,10,8,3,8,2)

In [22]:
#i
bar <- (foo[foo >= 5])
print(bar)

[1]  7  5  6 10  8  8


In [23]:
#ii
bar

[1]  7  5  6 10  8  8

In [24]:
foo[-which(x=foo>=5)]

[1] 1 2 3 2

### b

In [25]:
baz <- matrix(bar, nrow=2, ncol=3, byrow = TRUE)

In [26]:
print(baz)

     [,1] [,2] [,3]
[1,]    7    5    6
[2,]   10    8    8


In [27]:
baz==8

[,1]  [,2]  [,3] 
[1,] FALSE FALSE FALSE
[2,] FALSE  TRUE  TRUE

In [28]:
baz[1,2]^2

[1] 25

In [29]:
#i
baz[baz==8] <- baz[1,2]^2

In [30]:
baz

[,1] [,2] [,3]
[1,]  7    5    6  
[2,] 10   25   25

In [31]:
#ii
all(baz <= 25 & baz > 4)

[1] TRUE

### c

In [32]:
qux_vect <- c(10,5,1,4,7,4,3,3,1,3,4,3,1,7,8,3,7,3)

In [33]:
length(qux_vect)

[1] 18

In [34]:
qux <- array(qux_vect, dim=c(3,2,3))

In [35]:
print(qux)

, , 1

     [,1] [,2]
[1,]   10    4
[2,]    5    7
[3,]    1    4

, , 2

     [,1] [,2]
[1,]    3    3
[2,]    3    4
[3,]    1    3

, , 3

     [,1] [,2]
[1,]    1    3
[2,]    7    7
[3,]    8    3



In [36]:
#i
which(x=(qux==3 | qux==4), arr.ind = T)

dim1 dim2 dim3
 [1,] 1    2    1   
 [2,] 3    2    1   
 [3,] 1    1    2   
 [4,] 2    1    2   
 [5,] 1    2    2   
 [6,] 2    2    2   
 [7,] 3    2    2   
 [8,] 1    2    3   
 [9,] 3    2    3

In [37]:
#ii
qux[qux < 3 | qux >= 7] <- 100

In [38]:
print(qux)

, , 1

     [,1] [,2]
[1,]  100    4
[2,]    5  100
[3,]  100    4

, , 2

     [,1] [,2]
[1,]    3    3
[2,]    3    4
[3,]  100    3

, , 3

     [,1] [,2]
[1,]  100    3
[2,]  100  100
[3,]  100    3



### d

In [39]:
print(foo)

 [1]  7  5  6  1  2 10  8  3  8  2


In [40]:
foo[c(F,T)]

[1]  5  1 10  3  2

In [41]:
foo[c(0,1)]

[1] 7

You cannot use the integer equivalents of True and False, as r interprets the integers as positions of the array
that you would like to subset. In this case the items at positions 0 and 1.

## 4.4

### a

In [42]:
a <- "The quick brown fox"
b <- "jumped over"
c <- "the lazy dogs"

In [43]:
cat("\"",a, "\n    ", b, "\n        ", c, "\"", sep="")

"The quick brown fox
    jumped over
        the lazy dogs"

### b

In [44]:
num1 <- 4
num2 <- 0.75

In [45]:
paste("The result of multiplying ",num1, " by ", num2, " is ", num1 * num2, sep="")

[1] "The result of multiplying 4 by 0.75 is 3"

### c

In [46]:
DirectoryString <- "/Users/tdavies/Documents/RBook/"
sub(pattern="tdavies", replacement="jbuss", x=DirectoryString)

[1] "/Users/jbuss/Documents/RBook/"

### d

In [47]:
bar <- "How much wood could a woodchuck chuck"

In [48]:
#i
bar <- paste(bar, "if a woodchuck could chuck wood")

In [49]:
print(bar)

[1] "How much wood could a woodchuck chuck if a woodchuck could chuck wood"


In [50]:
#ii

In [51]:
gsub(pattern="wood", replacement="metal", x = bar)

[1] "How much metal could a metalchuck chuck if a metalchuck could chuck metal"

### e

In [52]:
BeerString <- "Two 6-packs for $12.99"
print(BeerString)

[1] "Two 6-packs for $12.99"


In [53]:
#i
substring(text = BeerString, first=5, last=10)

[1] "6-pack"

In [54]:
SixPackString <- "6-pack"

In [55]:
all.equal(SixPackString, substring(text = BeerString, first=5, last=10))

[1] TRUE

In [56]:
#ii
print(BeerString)

[1] "Two 6-packs for $12.99"


In [57]:
BetterDealString <- sub(pattern = "12.99", replacement = "10.99", x = BeerString)

In [58]:
BetterDealString

[1] "Two 6-packs for $10.99"

## 4.5

### a

In [59]:
sex.num <- c(0,1,1,1,0,0,0,1,1,1,1,0,1,0,0,0,1,1,1,1)

In [60]:
sex.char <- sex.num
sex.char[sex.char == 1] <- "male"
sex.char[sex.char == 0] <- "female"
print(sex.char)

 [1] "female" "male"   "male"   "male"   "female" "female" "female" "male"  
 [9] "male"   "male"   "male"   "female" "male"   "female" "female" "female"
[17] "male"   "male"   "male"   "male"  


In [61]:
party.char <- c(1:20)
print(party.char)

 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20


In [62]:
party.char[c(1,4,12,15,16,19)] <- "Labour"
party.char[c(6,9,11)] <- "Green"
party.char[c(10,20)] <- "Other"
party.char[party.char <= 9] <- "National"
party.char

[1] "Labour"   "National" "National" "Labour"   "National" "Green"   
 [7] "National" "National" "Green"    "Other"    "Green"    "Labour"  
[13] "National" "National" "Labour"   "Labour"   "National" "National"
[19] "Labour"   "Other"

### b

In [92]:
sex.char.fac <- factor(x=sex.char)
sex.char.fac

[1] female male   male   male   female female female male   male   male  
[11] male   female male   female female female male   male   male   male  
Levels: female male

In [93]:
party.char.fac <- factor(x=party.char)
party.char.fac

[1] Labour   National National Labour   National Green    National National
 [9] Green    Other    Green    Labour   National National Labour   Labour  
[17] National National Labour   Other   
Levels: Green Labour National Other

In [94]:
# Ordered is not needed. r has arranged them alphabetically

### c

In [95]:
#i
party.char.fac[sex.char.fac == "male"]

[1] National National Labour   National Green    Other    Green    National
 [9] National National Labour   Other   
Levels: Green Labour National Other

In [96]:
#ii
sex.char.fac[party.char.fac=="National"]

[1] male   male   female female male   male   female male   male  
Levels: female male

### d

In [97]:
new.sex.char.fac <- factor(
    x=c("male","male","female","female","female","male"), 
    levels=levels(sex.char.fac)
)
print(new.sex.char.fac)

[1] male   male   female female female male  
Levels: female male


In [98]:
sex.char.fac <- levels(sex.char.fac)[c(sex.char.fac,new.sex.char.fac)]

In [99]:
length(sex.char.fac)
sex.char.fac

[1] 26

[1] "female" "male"   "male"   "male"   "female" "female" "female" "male"  
 [9] "male"   "male"   "male"   "female" "male"   "female" "female" "female"
[17] "male"   "male"   "male"   "male"   "male"   "male"   "female" "female"
[25] "female" "male"

In [100]:
new.party.char.fac <- factor(
    x=c("National","Maori","Maori","Labour","Green","Labour"), 
    levels=c(levels(party.char.fac),"Maori")
)
print(new.party.char.fac)

[1] National Maori    Maori    Labour   Green    Labour  
Levels: Green Labour National Other Maori


In [101]:
party.char.fac <- c(levels(party.char.fac),"Maori")[c(party.char.fac,new.party.char.fac)]

In [102]:
length(party.char.fac)
party.char.fac

[1] 26

[1] "Labour"   "National" "National" "Labour"   "National" "Green"   
 [7] "National" "National" "Green"    "Other"    "Green"    "Labour"  
[13] "National" "National" "Labour"   "Labour"   "National" "National"
[19] "Labour"   "Other"    "National" "Maori"    "Maori"    "Labour"  
[25] "Green"    "Labour"

### e

In [103]:
LabourConf.values <- c(93,55,29,100,52,84,56,0,33,52,35,53,55,46,40,40,56,45,64,31,10,29,40,95,18,61)

In [104]:
br <- c(0,30,70,100)
lab <- c("Low","Moderate","High")
LabourConf.values.fac <- cut(x=LabourConf.values, breaks=br,right=T,include.lowest=T,labels=lab)

### f

In [108]:
LabourConf.values.fac[party.char.fac == "Labour"]

[1] High     High     Moderate Moderate Moderate Moderate High     Moderate
Levels: Low Moderate High

In [109]:
LabourConf.values.fac[party.char.fac == "National"]

[1] Moderate Low      Moderate Moderate Low      Moderate Moderate Moderate
 [9] Moderate Low     
Levels: Low Moderate High

Those that claim to be in the Labour party have a high degree of certainty that the 
Labour party will pick up seats. 