# 3.1

## a

In [8]:
avec <- c(4.3, 3.1, 8.2, 8.2, 3.2, 0.9, 1.6, 6.5)
amat <- matrix(avec, nrow=4, ncol=2, byrow=TRUE)
amat

[,1] [,2]
[1,] 4.3  3.1 
[2,] 8.2  8.2 
[3,] 3.2  0.9 
[4,] 1.6  6.5

  ## b

In [10]:
dim(amat)

[1] 4 2

In [13]:
dim(amat[-3,])

[1] 3 2

## c

In [17]:
amat[,2]<-sort(amat[,2])

In [18]:
amat

[,1] [,2]
[1,] 4.3  0.9 
[2,] 8.2  3.1 
[3,] 3.2  6.5 
[4,] 1.6  8.2

## d

In [23]:
amat[-4,-2]

[1] 4.3 8.2 3.2

In [24]:
matrix(amat[-4,-2])

[,1]
[1,] 4.3 
[2,] 8.2 
[3,] 3.2

## e

In [26]:
emat <- amat[3:4,1:2]

In [27]:
emat

[,1] [,2]
[1,] 3.2  6.5 
[2,] 1.6  8.2

## f

In [28]:
amat

[,1] [,2]
[1,] 4.3  0.9 
[2,] 8.2  3.1 
[3,] 3.2  6.5 
[4,] 1.6  8.2

In [30]:
diag(emat)*-0.5

[1] -1.6 -4.1

In [41]:
amat[c(4,1),c(2,1)] <- diag(emat)*-0.5

In [42]:
amat

[,1] [,2]
[1,] -4.1 -4.1
[2,]  8.2  3.1
[3,]  3.2  6.5
[4,] -1.6 -1.6

## 3.2

### a

In [48]:
amat_1 = matrix(c(1, 2, 7, 2, 4, 6), nrow=3, ncol=2)
amat_2 = matrix(c(10, 30, 50, 20, 40, 60), nrow=3, ncol=2)
(2/7)*(amat_1 - amat_2)

[,1]       [,2]      
[1,]  -2.571429  -5.142857
[2,]  -8.000000 -10.285714
[3,] -12.285714 -15.428571

### b

In [49]:
A = matrix(c(1,2,7))
B = matrix(c(3,4,8))

In [64]:
# i - No
# ii - yes
t(A)%*%B
# iii - yes
A %*% t(A)
# iiii -no
# v 
solve((B %*% t(B)) + (A %*% t(A)) - 100 * diag(x = 3))

[,1]
[1,] 67

[,1] [,2] [,3]
[1,] 1     2    7  
[2,] 2     4   14  
[3,] 7    14   49

[,1]         [,2]         [,3]       
[1,] -0.007923676  0.003123274 0.007843334
[2,]  0.003123274 -0.005350239 0.011483806
[3,]  0.007843334  0.011483806 0.017584735

### c

In [68]:
A <- diag(x=c(2,3,5,-1))
print(A)

     [,1] [,2] [,3] [,4]
[1,]    2    0    0    0
[2,]    0    3    0    0
[3,]    0    0    5    0
[4,]    0    0    0   -1


In [71]:
solve(A) %*% A - diag(x=4)

[,1] [,2] [,3] [,4]
[1,] 0    0    0    0   
[2,] 0    0    0    0   
[3,] 0    0    0    0   
[4,] 0    0    0    0

## 3.3

### a

In [80]:
a_array <- array(data=seq(from=4.8, to=0.1, length.out=48), dim=c(4,2,6))

In [81]:
a_array

, , 1

     [,1] [,2]
[1,]  4.8  4.4
[2,]  4.7  4.3
[3,]  4.6  4.2
[4,]  4.5  4.1

, , 2

     [,1] [,2]
[1,]  4.0  3.6
[2,]  3.9  3.5
[3,]  3.8  3.4
[4,]  3.7  3.3

, , 3

     [,1] [,2]
[1,]  3.2  2.8
[2,]  3.1  2.7
[3,]  3.0  2.6
[4,]  2.9  2.5

, , 4

     [,1] [,2]
[1,]  2.4  2.0
[2,]  2.3  1.9
[3,]  2.2  1.8
[4,]  2.1  1.7

, , 5

     [,1] [,2]
[1,]  1.6  1.2
[2,]  1.5  1.1
[3,]  1.4  1.0
[4,]  1.3  0.9

, , 6

     [,1] [,2]
[1,]  0.8  0.4
[2,]  0.7  0.3
[3,]  0.6  0.2
[4,]  0.5  0.1

### b

In [90]:
b_array <- a_array[c(4,1),2,]
print(b_array)

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]  4.1  3.3  2.5  1.7  0.9  0.1
[2,]  4.4  3.6  2.8  2.0  1.2  0.4


### c

In [92]:
c_array <- array(data=b_array[2,],dim=c(2,2,2,3))

In [95]:
# Example - First Layer of first block
c_array[,,1,1]

[,1] [,2]
[1,] 4.4  2.8 
[2,] 3.6  2.0

### d

In [103]:
d_array <- array(data=a_array[,,-6],dim=c(4,2,5))

In [104]:
d_array

, , 1

     [,1] [,2]
[1,]  4.8  4.4
[2,]  4.7  4.3
[3,]  4.6  4.2
[4,]  4.5  4.1

, , 2

     [,1] [,2]
[1,]  4.0  3.6
[2,]  3.9  3.5
[3,]  3.8  3.4
[4,]  3.7  3.3

, , 3

     [,1] [,2]
[1,]  3.2  2.8
[2,]  3.1  2.7
[3,]  3.0  2.6
[4,]  2.9  2.5

, , 4

     [,1] [,2]
[1,]  2.4  2.0
[2,]  2.3  1.9
[3,]  2.2  1.8
[4,]  2.1  1.7

, , 5

     [,1] [,2]
[1,]  1.6  1.2
[2,]  1.5  1.1
[3,]  1.4  1.0
[4,]  1.3  0.9

### e

In [105]:
dim(d_array)

[1] 4 2 5

In [106]:
d_array[,,1]

[,1] [,2]
[1,] 4.8  4.4 
[2,] 4.7  4.3 
[3,] 4.6  4.2 
[4,] 4.5  4.1

In [109]:
d_array[c(2,4),2,c(1,3,5)] <- -99

In [113]:
# example
d_array[,,3]

[,1] [,2] 
[1,] 3.2    2.8
[2,] 3.1  -99.0
[3,] 3.0    2.6
[4,] 2.9  -99.0